version: "3.8"
services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - front-end
      - server
      - server2
      - server3

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  front-end:
    image: ghcr.io/mcmastercce/bvd-103-mcmasterful-books/mcmasterful-books-docker:main
    volumes:
      - ./adapter:/source/adapter

  server:
    image: node:20
    volumes:
      - ./:/app
    working_dir: /app
    command: npx -y tsx src/server.ts
    depends_on:
      - mongo

  server2:
    image: node:20
    volumes:
      - ./:/app
    working_dir: /app
    command: npx -y tsx src/server.ts
    depends_on:
      - mongo

  server3:
    image: node:20
    volumes:
      - ./:/app
    working_dir: /app
    command: npx -y tsx src/server.ts
    depends_on:
      - mongo
