services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - front-end
      - server
      - server2
      - server3
      - server4

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  front-end:
    image: ghcr.io/mcmastercce/bvd-103-mcmasterful-books/mcmasterful-books-docker:main
    volumes:
      - ./adapter:/source/adapter

  server:
    image: node:20
    volumes:
      - ./:/app
    working_dir: /app
    command: npx -y tsx src/server.ts
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  server2:
    image: node:20
    volumes:
      - ./orders-service:/app
    working_dir: /app
    command: npx -y tsx src/server.ts
    ports:
      - "3001:3000"
    depends_on:
      - mongo
      - rabbitmq
    environment:
      - USE_DOCKER=true
  server3:
    image: node:20
    volumes:
      - ./warehouse-service:/app
    working_dir: /app
    command: npx -y tsx src/server.ts
    ports:
      - "3002:3000"
    depends_on:
      - mongo
      - rabbitmq
    environment:
      - USE_DOCKER=true
  server4:
    image: node:20
    volumes:
      - ./listings-service:/app
    working_dir: /app
    command: npx -y tsx src/server.ts
    ports:
      - "3003:3000"
    depends_on:
      - mongo
      - rabbitmq
    environment:
      - USE_DOCKER=true
      - RABBITMQ_HOST=rabbitmq