GET http://localhost:3000/books HTTP/1.1
User-Agent: vscode-restclient
accept-encoding: gzip, deflate


HTTP/1.1 500 Internal Server Error
Vary: Origin
Access-Control-Allow-Origin: *
Content-Type: application/json; charset=utf-8
Content-Length: 53
Date: Sat, 10 May 2025 16:47:00 GMT
Connection: close

{
  "error": "Failed to fetch books due to: Error: Todo"
}