name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm ci

      - name: Set execute permissions for generate-openapi.sh
        run: chmod +x ./generate-openapi.sh

      - run: npm run lint

  format:
    name: Check Prettier Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm ci

      - run: npm run format -- --check

  type-check:
    name: Run TypeScript Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm ci
      - name: Set execute permissions for generate-openapi.sh
        run: chmod +x ./generate-openapi.sh
      - run: npm run type-check

  unit-test:
    name: Run Unit/Standard Tests
    needs: [lint, format, type-check]
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongosh --eval 'db.adminCommand(\"ping\")'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm ci
      - name: Set execute permissions for generate-openapi.sh
        run: chmod +x ./generate-openapi.sh
      - name: Generate OpenAPI Spec and Client SDK
        run: ./generate-openapi.sh

      - name: Run standard tests
        run: npx vitest --excludeTag api
        env:
          MONGO_URI: mongodb://localhost:27017/booksdb

  api-test:
    name: Run API Tests
    needs: [unit-test]
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongosh --eval 'db.adminCommand(\"ping\")'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm ci

      - name: Set execute permissions for generate-openapi.sh
        run: chmod +x ./generate-openapi.sh

      - name: Generate OpenAPI Spec and Client SDK
        run: ./generate-openapi.sh

      - name: Start API server
        run: npm run start &
        env:
          MONGO_URI: mongodb://localhost:27017/booksdb

      - name: Wait for server to be ready
        run: |
          for i in {1..10}; do
            curl --silent http://localhost:3000/health && break
            sleep 2
          done

      - name: Run API tests
        run: npx vitest --tag api
        env:
          MONGO_URI: mongodb://localhost:27017/booksdb

      - name: Upload Client SDK
        uses: actions/upload-artifact@v3
        with:
          name: client-sdk
          path: client/
