name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  release:
    types: [created]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    strategy:
      matrix:
        service: [listings-service, warehouse-service, orders-service, mcmasterful-books-docker]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          SERVICE_DIR=${{ matrix.service }}
          if [ "$SERVICE_DIR" = "mcmasterful-books-docker" ]; then
            docker build -t ghcr.io/${{ github.repository_owner }}/$SERVICE_DIR ./
          else
            docker build -t ghcr.io/${{ github.repository_owner }}/$SERVICE_DIR ./$SERVICE_DIR
          fi
          docker push ghcr.io/${{ github.repository_owner }}/$SERVICE_DIR
