name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  release:
    types: [created]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    strategy:
      matrix:
        service: [listings-service, warehouse-service, orders-service]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/${{ matrix.service }}
          docker build -t $IMAGE_NAME ./$(echo ${{ matrix.service }})
          docker push $IMAGE_NAME
